Temporarily use matplotlib<3.9 to avoid PolyFuzz error
PolyFuzz is being installed as a transitive dependency, and the
following error happens due to the removal of `matplotlib.cm.get_cmap`
in matplotlib 3.9. We can remove the restriction when PolyFuzz releases
a version that fixes the issue

/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/polyfuzz/__init__.py:1:
in <module>
    from .polyfuzz import PolyFuzz
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/polyfuzz/polyfuzz.py:9:
in <module>
from polyfuzz.metrics import precision_recall_curve,
visualize_precision_recall
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/polyfuzz/metrics.py:8:
in <module>
    from matplotlib.cm import get_cmap
E   ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'
(/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/matplotlib/cm.py)