Temporarily use scipy<1.13 to avoid import error of triu package
Pinning scipy to version lower than 1.13 to avoid the following error:
ImportError: cannot import name 'triu' from 'scipy.linalg'
(/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/scipy/linalg/__init__.py)

This version restriction can be removed when packages that depend on
triu are fixed. See e.g.:
- https://github.com/piskvorky/gensim/pull/3524
- https://github.com/scipy/scipy/issues/20402